# -*- coding: utf-8 -*-
"""DL_Lab2-Study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149RP876eJlNWnAMnmtsPmv480cdNHoR7

Assignment 2
Implement Simple and Multiple Linear Regression to predict continuous variables. a.
Perform data preprocessing (handle missing values, feature scaling). b. Fit a Simple
Linear Regression model on a dataset (e.g., predicting house prices). c. Extend to
Multiple Linear Regression with multiple features. d. Evaluate models using MSE,
RMSE, and R² Score. e. Visualize the regression line and predictions.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import os

import kagglehub

path = kagglehub.dataset_download("farhanmd29/50-startups")

print("Path to dataset files:", path)

file_path = os.path.join(path, "50_Startups.csv")
data = pd.read_csv(file_path)

data.head()

data = data.fillna(data.mean(numeric_only=True))

data = pd.get_dummies(data, drop_first=True)

scaler = StandardScaler()
X = data.drop("Profit", axis=1)
y = data["Profit"]
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
X_scaled, y, test_size=0.2, random_state=42
)

X_simple = data[["R&D Spend"]]
data = data.fillna(data.mean(numeric_only=True))
data = pd.get_dummies(data, drop_first=True)
scaler = StandardScaler()
X = data.drop("Profit", axis=1)
y = data["Profit"]
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(
X_scaled, y, test_size=0.2, random_state=42
)
X_simple_scaled = scaler.fit_transform(X_simple)
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
X_simple_scaled, y, test_size=0.2, random_state=42
)

model_simple = LinearRegression()
model_simple.fit(X_train_s, y_train_s)

y_pred_simple = model_simple.predict(X_test_s)

mse_s = mean_squared_error(y_test_s, y_pred_simple)
rmse_s = np.sqrt(mse_s)
r2_s = r2_score(y_test_s, y_pred_simple)
print("Simple Linear Regression:")
print("MSE:", mse_s)
print("RMSE:", rmse_s)
print("R2:", r2_s)

plt.scatter(X_test_s, y_test_s, color="blue")
plt.plot(X_test_s, y_pred_simple, color="red")
plt.xlabel("R&D Spend")
plt.ylabel("Profit")
plt.title("Simple Linear Regression (R&D Spend vs Profit)")
plt.show()

model_multi = LinearRegression()
model_multi.fit(X_train, y_train)
y_pred_multi = model_multi.predict(X_test)
mse_m = mean_squared_error(y_test, y_pred_multi)
rmse_m = np.sqrt(mse_m)
r2_m = r2_score(y_test, y_pred_multi)
print("\nMultiple Linear Regression:")
print("MSE:", mse_m)
print("RMSE:", rmse_m)
print("R2:", r2_m)

plt.scatter(y_test, y_pred_multi)
plt.xlabel("Actual Profit")
plt.ylabel("Predicted Profit")
plt.title("Multiple Linear Regression")
plt.show()

"""Conclusion
The 50_Startups dataset was used to predict startup profit.
Data preprocessing included missing value handling, encoding categorical data, and
feature scaling.
4/5
https://colab.research.google.com/drive/1FoIqISxZxnE9h-YiSszsYAtxPI46QOdt#scrollTo=RbT8yss6U7qW&printMode=true
1/30/26, 4:55 PM
DL Assignment 2.ipynb - Colab
Simple Linear Regression analyzed the effect of R&D spend on profit.
Multiple Linear Regression used all relevant expenditures and state information.
Performance was evaluated using MSE, RMSE, and R² score.
Multiple Linear Regression achieved better accuracy due to multiple contributing
factors.
"""

