# -*- coding: utf-8 -*-
"""DL_Lab10-Study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZ9s1h91FOfo5XtLdWTJKN5y06NJbGCx

DL Assignment 10

Name - Neel Sahasrabudhe

Class - CS(AI) B

Batch - 01

Roll no - 27

PRN - 12311847
Assignment 10: Using LSTM for prediction of future weather of cities in Python
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("sumanthvrao/daily-climate-time-series-data")

print("Path to dataset files:", path)

import pandas as pd
import os

path = "/root/.cache/kagglehub/datasets/sumanthvrao/daily-climate-time-series-data/versions/3"

print(os.listdir(path))

df = pd.read_csv(os.path.join(path, "DailyDelhiClimateTrain.csv"))

df.head()

print(df.info())
print(df.describe())

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.plot(df['meantemp'])
plt.title("Temperature Over Time")
plt.xlabel("Days")
plt.ylabel("Temperature")
plt.show()

from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = df[['meantemp']].values

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

X = []
y = []

time_step = 30

for i in range(time_step, len(scaled_data)):
    X.append(scaled_data[i-time_step:i, 0])
    y.append(scaled_data[i, 0])

X, y = np.array(X), np.array(y)

X = X.reshape(X.shape[0], X.shape[1], 1)

print("Shape of X:", X.shape)

split = int(0.8 * len(X))

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

model = Sequential()

model.add(LSTM(50, return_sequences=True, input_shape=(X.shape[1],1)))
model.add(LSTM(50))
model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32
)

predictions = model.predict(X_test)

# Convert back to original scale
predictions = scaler.inverse_transform(predictions)
y_test_actual = scaler.inverse_transform(y_test.reshape(-1,1))

plt.figure(figsize=(10,5))

plt.plot(y_test_actual, label='Actual Temperature')
plt.plot(predictions, label='Predicted Temperature')

plt.legend()
plt.title("Weather Prediction using LSTM")
plt.show()

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test_actual, predictions)
rmse = np.sqrt(mse)

print("RMSE:", rmse)