# -*- coding: utf-8 -*-
"""DL_Lab8-Study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LokjbYCgTFrGp8pwSyy9qmMVbpO_cfLb

DL Assignment 08

Name - Neel Sahasrabudhe

Class - CS(AI) B

Batch - 01

Roll no - 27

PRN - 12311847
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np

fashion_mnist = tf.keras.datasets.fashion_mnist

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

X_train = X_train / 255.0
X_test = X_test / 255.0

X_train = X_train.reshape(-1,28,28,1)
X_test = X_test.reshape(-1,28,28,1)

model = models.Sequential()

# Convolution Layer 1
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))
model.add(layers.MaxPooling2D(2,2))

# Convolution Layer 2
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D(2,2))

# Flatten
model.add(layers.Flatten())

# Dense Layer
model.add(layers.Dense(128, activation='relu'))

# Output Layer
model.add(layers.Dense(10, activation='softmax'))

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train, y_train,
    epochs=9,
    validation_data=(X_test, y_test)
)

history = model.fit(
    X_train, y_train,
    epochs=10,
    validation_data=(X_test, y_test)
)

test_loss, test_acc = model.evaluate(X_test, y_test)

print("Test Accuracy:", test_acc)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.legend(['Train','Validation'])
plt.title("Model Accuracy")
plt.show()

predictions = model.predict(X_test)

print("Predicted Class:", np.argmax(predictions[0]))
print("Actual Class:", y_test[0])

plt.imshow(X_test[0].reshape(28,28), cmap='gray')
plt.title("Sample Image")
plt.show()

