# -*- coding: utf-8 -*-
"""DL_Lab3-Study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8Vu1-440FFQNSHFAEKwGvEX-Gb7eMas

Assignment No. 3 : Write a program to implement k-Nearest Neighbour algorithm to classify the iris data set. Print both correct and wrong predictions. Python ML library classes can be used for this problem
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

iris = load_iris()
X = iris.data
y = iris.target

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=91
)

k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

y_pred = []

for i in range(len(X_test)):
    pred = knn.predict([X_test[i]])
    y_pred.append(pred[0])

print("Index\tActual\t\tPredicted")
print("--------------------------------------")

correct = 0

for i in range(len(y_test)):
    actual_label = iris.target_names[y_test[i]]
    predicted_label = iris.target_names[y_pred[i]]

    print(f"{i}\t{actual_label}\t{predicted_label}")

    if y_test[i] == y_pred[i]:
        correct += 1

manual_accuracy = correct / len(y_test)
print("\nManual Accuracy:", manual_accuracy)

print("\nSklearn Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n",
      classification_report(y_test, y_pred, target_names=iris.target_names))



