# -*- coding: utf-8 -*-
"""DL_Lab1-Study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dnNrEpQJJKgnpGfNZg3N4c8cIWFsf35H

Name:Kavish Paraswar  S

Class: TY CSAI B batch 1

Roll no: 2

PRN:12311694

Assignment No. 1 Perform PCA in dimension reduction of numerical data

Pre-process the data through standardization.
Perform PCA to reduce dimension.
Construct the scree plot.
Data visualization in lower dimensional representation.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Load numerical dataset
data = pd.DataFrame({
    'Feature1': [2.5, 0.5, 2.2, 1.9, 3.1],
    'Feature2': [2.4, 0.7, 2.9, 2.2, 3.0],
    'Feature3': [1.1, 0.3, 1.5, 1.3, 1.9]
})
print("Original Dataset:");
print(data);

#1. Standardization
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print("Standardized Dataset:");
print(scaled_data);

#2. PCA
pca = PCA()
pca_data = pca.fit_transform(scaled_data)

#3. Scree Plot
explained_variance = pca.explained_variance_ratio_

print("\nExplained Variance Ratio:");
print(explained_variance);

plt.figure(figsize=(6,4))
plt.plot(np.cumsum(explained_variance), marker='o')
plt.xlabel('Number of Principal Components')
plt.ylabel('Cumulative Explained Variance')
plt.title('Scree Plot')
plt.grid()
plt.show()

#4. Dimensionality Reduction to 2D
pca_2 = PCA(n_components=2)
reduced_data = pca_2.fit_transform(scaled_data)

#5. 2D Visualization
plt.figure(figsize=(6,5))
plt.scatter(reduced_data[:, 0], reduced_data[:, 1])
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA – 2D Data Visualization')
plt.grid()
plt.show()

